-- ============================================
-- POPULAR CAMADA FINAL A PARTIR DA STAGING
-- ============================================
-- REGRA:
-- ENTRA NA CAMADA FINAL APENAS O QUE ESTIVER:
-- STATUS = 'COMPLETA'
-- E ALTERNATIVAS_COMPLETAS = TRUE
-- ============================================


-- ============================================
-- 1) QUESTAO
-- ============================================
INSERT INTO QUESTAO (
    PROVA_ID,
    NUMERO,
    ENUNCIADO,
    TIPO
)
SELECT
    QS.PROVA_ID,
    QS.NUMERO,
    QS.ENUNCIADO,
    'OBJETIVA'
FROM QUESTAO_STAGING QS
WHERE QS.STATUS = 'COMPLETA'
  AND QS.ALTERNATIVAS_COMPLETAS = TRUE
ON CONFLICT (PROVA_ID, NUMERO)
DO UPDATE SET
    ENUNCIADO = EXCLUDED.ENUNCIADO,
    TIPO = EXCLUDED.TIPO;


-- ============================================
-- 2) ALTERNATIVA
-- ============================================

-- A
INSERT INTO ALTERNATIVA (
    QUESTAO_ID,
    LETRA,
    TEXTO
)
SELECT
    Q.ID,
    'A',
    QS.ALTERNATIVA_A
FROM QUESTAO_STAGING QS
JOIN QUESTAO Q
    ON Q.PROVA_ID = QS.PROVA_ID
   AND Q.NUMERO = QS.NUMERO
WHERE QS.STATUS = 'COMPLETA'
  AND QS.ALTERNATIVAS_COMPLETAS = TRUE
  AND QS.ALTERNATIVA_A IS NOT NULL
ON CONFLICT (QUESTAO_ID, LETRA)
DO UPDATE SET
    TEXTO = EXCLUDED.TEXTO;

-- B
INSERT INTO ALTERNATIVA (
    QUESTAO_ID,
    LETRA,
    TEXTO
)
SELECT
    Q.ID,
    'B',
    QS.ALTERNATIVA_B
FROM QUESTAO_STAGING QS
JOIN QUESTAO Q
    ON Q.PROVA_ID = QS.PROVA_ID
   AND Q.NUMERO = QS.NUMERO
WHERE QS.STATUS = 'COMPLETA'
  AND QS.ALTERNATIVAS_COMPLETAS = TRUE
  AND QS.ALTERNATIVA_B IS NOT NULL
ON CONFLICT (QUESTAO_ID, LETRA)
DO UPDATE SET
    TEXTO = EXCLUDED.TEXTO;

-- C
INSERT INTO ALTERNATIVA (
    QUESTAO_ID,
    LETRA,
    TEXTO
)
SELECT
    Q.ID,
    'C',
    QS.ALTERNATIVA_C
FROM QUESTAO_STAGING QS
JOIN QUESTAO Q
    ON Q.PROVA_ID = QS.PROVA_ID
   AND Q.NUMERO = QS.NUMERO
WHERE QS.STATUS = 'COMPLETA'
  AND QS.ALTERNATIVAS_COMPLETAS = TRUE
  AND QS.ALTERNATIVA_C IS NOT NULL
ON CONFLICT (QUESTAO_ID, LETRA)
DO UPDATE SET
    TEXTO = EXCLUDED.TEXTO;

-- D
INSERT INTO ALTERNATIVA (
    QUESTAO_ID,
    LETRA,
    TEXTO
)
SELECT
    Q.ID,
    'D',
    QS.ALTERNATIVA_D
FROM QUESTAO_STAGING QS
JOIN QUESTAO Q
    ON Q.PROVA_ID = QS.PROVA_ID
   AND Q.NUMERO = QS.NUMERO
WHERE QS.STATUS = 'COMPLETA'
  AND QS.ALTERNATIVAS_COMPLETAS = TRUE
  AND QS.ALTERNATIVA_D IS NOT NULL
ON CONFLICT (QUESTAO_ID, LETRA)
DO UPDATE SET
    TEXTO = EXCLUDED.TEXTO;

-- E
INSERT INTO ALTERNATIVA (
    QUESTAO_ID,
    LETRA,
    TEXTO
)
SELECT
    Q.ID,
    'E',
    QS.ALTERNATIVA_E
FROM QUESTAO_STAGING QS
JOIN QUESTAO Q
    ON Q.PROVA_ID = QS.PROVA_ID
   AND Q.NUMERO = QS.NUMERO
WHERE QS.STATUS = 'COMPLETA'
  AND QS.ALTERNATIVAS_COMPLETAS = TRUE
  AND QS.ALTERNATIVA_E IS NOT NULL
ON CONFLICT (QUESTAO_ID, LETRA)
DO UPDATE SET
    TEXTO = EXCLUDED.TEXTO;


-- ============================================
-- 3) GABARITO
-- ============================================
INSERT INTO GABARITO (
    QUESTAO_ID,
    RESPOSTA
)
SELECT
    Q.ID,
    QS.GABARITO_RESPOSTA
FROM QUESTAO_STAGING QS
JOIN QUESTAO Q
    ON Q.PROVA_ID = QS.PROVA_ID
   AND Q.NUMERO = QS.NUMERO
WHERE QS.STATUS = 'COMPLETA'
  AND QS.ALTERNATIVAS_COMPLETAS = TRUE
  AND QS.GABARITO_RESPOSTA IS NOT NULL
ON CONFLICT (QUESTAO_ID)
DO UPDATE SET
    RESPOSTA = EXCLUDED.RESPOSTA;


-- ============================================
-- 4) VALIDAÇÕES
-- ============================================

SELECT 'QUESTAO' AS TABELA, COUNT(*) AS TOTAL
FROM QUESTAO

UNION ALL

SELECT 'ALTERNATIVA' AS TABELA, COUNT(*) AS TOTAL
FROM ALTERNATIVA

UNION ALL

SELECT 'GABARITO' AS TABELA, COUNT(*) AS TOTAL
FROM GABARITO;