-- ============================================
-- RESET OPCIONAL
-- ============================================
-- USE ESTE BLOCO SOMENTE SE QUISER RECRIAR TUDO DO ZERO
-- DROP TABLE IF EXISTS GABARITO CASCADE;
-- DROP TABLE IF EXISTS ALTERNATIVA CASCADE;
-- DROP TABLE IF EXISTS QUESTAO CASCADE;
-- DROP TABLE IF EXISTS QUESTAO_STAGING CASCADE;
-- DROP TABLE IF EXISTS PROVA CASCADE;
-- DROP TABLE IF EXISTS CURSO CASCADE;
-- DROP TABLE IF EXISTS ANO CASCADE;

-- ============================================
-- TABELAS BÁSICAS
-- ============================================

CREATE TABLE IF NOT EXISTS ANO (
    ID SERIAL PRIMARY KEY,
    VALOR INTEGER NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS CURSO (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL UNIQUE
);

-- UMA PROVA LÓGICA POR ANO + CURSO
-- AQUI FICAM OS CAMINHOS E URLs DOS DOIS PDFs:
-- PROVA (PV) E GABARITO (GB)
CREATE TABLE IF NOT EXISTS PROVA (
    ID SERIAL PRIMARY KEY,
    ANO_ID INTEGER NOT NULL REFERENCES ANO(ID),
    CURSO_ID INTEGER NOT NULL REFERENCES CURSO(ID),
    TITULO VARCHAR(500),
    URL_PDF_PROVA TEXT,
    URL_PDF_GABARITO TEXT,
    CAMINHO_PDF_PROVA TEXT,
    CAMINHO_PDF_GABARITO TEXT,
    VERSAO_PARSER VARCHAR(20) NOT NULL DEFAULT 'V2',
    CRIADO_EM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (ANO_ID, CURSO_ID)
);

-- ============================================
-- CAMADA STAGING
-- ============================================
-- ESTA TABELA RECEBE O RESULTADO BRUTO DO PARSER
-- AQUI PODEM ENTRAR QUESTÕES COMPLETAS, INCOMPLETAS,
-- FORA DE ESCOPO OU NÃO ENCONTRADAS
CREATE TABLE IF NOT EXISTS QUESTAO_STAGING (
    ID SERIAL PRIMARY KEY,
    PROVA_ID INTEGER NOT NULL REFERENCES PROVA(ID) ON DELETE CASCADE,
    NUMERO INTEGER NOT NULL,
    GABARITO_RESPOSTA CHAR(1) CHECK (GABARITO_RESPOSTA IN ('A', 'B', 'C', 'D', 'E')),
    STATUS VARCHAR(20) NOT NULL CHECK (
        STATUS IN ('COMPLETA', 'INCOMPLETA', 'FORA_ESCOPO', 'NAO_ENCONTRADA')
    ),
    CONFIANCA VARCHAR(10) CHECK (
        CONFIANCA IN ('ALTA', 'MEDIA', 'BAIXA')
    ),
    PARSE_STRATEGY VARCHAR(100),
    ENUNCIADO TEXT,
    ALTERNATIVA_A TEXT,
    ALTERNATIVA_B TEXT,
    ALTERNATIVA_C TEXT,
    ALTERNATIVA_D TEXT,
    ALTERNATIVA_E TEXT,
    ALTERNATIVAS_COMPLETAS BOOLEAN NOT NULL DEFAULT FALSE,
    TEXTO_BRUTO TEXT,
    OBSERVACAO TEXT,
    VERSAO_PARSER VARCHAR(20) NOT NULL DEFAULT 'V2',
    CRIADO_EM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (PROVA_ID, NUMERO, VERSAO_PARSER)
);

-- ============================================
-- CAMADA FINAL NORMALIZADA
-- ============================================
-- A IDEIA É POPULAR ESTAS TABELAS APENAS COM
-- QUESTÕES APROVADAS DA STAGING
CREATE TABLE IF NOT EXISTS QUESTAO (
    ID SERIAL PRIMARY KEY,
    PROVA_ID INTEGER NOT NULL REFERENCES PROVA(ID) ON DELETE CASCADE,
    NUMERO INTEGER NOT NULL,
    ENUNCIADO TEXT NOT NULL,
    TIPO VARCHAR(20) NOT NULL DEFAULT 'OBJETIVA' CHECK (
        TIPO IN ('OBJETIVA')
    ),
    CRIADO_EM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (PROVA_ID, NUMERO)
);

CREATE TABLE IF NOT EXISTS ALTERNATIVA (
    ID SERIAL PRIMARY KEY,
    QUESTAO_ID INTEGER NOT NULL REFERENCES QUESTAO(ID) ON DELETE CASCADE,
    LETRA CHAR(1) NOT NULL CHECK (LETRA IN ('A', 'B', 'C', 'D', 'E')),
    TEXTO TEXT NOT NULL,
    UNIQUE (QUESTAO_ID, LETRA)
);

CREATE TABLE IF NOT EXISTS GABARITO (
    ID SERIAL PRIMARY KEY,
    QUESTAO_ID INTEGER NOT NULL UNIQUE REFERENCES QUESTAO(ID) ON DELETE CASCADE,
    RESPOSTA CHAR(1) NOT NULL CHECK (RESPOSTA IN ('A', 'B', 'C', 'D', 'E'))
);

-- ============================================
-- ÍNDICES ÚTEIS
-- ============================================

CREATE INDEX IF NOT EXISTS IDX_PROVA_ANO_ID
    ON PROVA (ANO_ID);

CREATE INDEX IF NOT EXISTS IDX_PROVA_CURSO_ID
    ON PROVA (CURSO_ID);

CREATE INDEX IF NOT EXISTS IDX_QUESTAO_STAGING_PROVA_ID
    ON QUESTAO_STAGING (PROVA_ID);

CREATE INDEX IF NOT EXISTS IDX_QUESTAO_STAGING_STATUS
    ON QUESTAO_STAGING (STATUS);

CREATE INDEX IF NOT EXISTS IDX_QUESTAO_STAGING_NUMERO
    ON QUESTAO_STAGING (NUMERO);

CREATE INDEX IF NOT EXISTS IDX_QUESTAO_PROVA_ID
    ON QUESTAO (PROVA_ID);

CREATE INDEX IF NOT EXISTS IDX_ALTERNATIVA_QUESTAO_ID
    ON ALTERNATIVA (QUESTAO_ID);

-- ============================================
-- CONSULTAS DE VALIDAÇÃO
-- ============================================

SELECT * FROM ANO;
SELECT * FROM CURSO;
SELECT * FROM PROVA;
SELECT * FROM QUESTAO_STAGING;
SELECT * FROM QUESTAO;
SELECT * FROM ALTERNATIVA;
SELECT * FROM GABARITO;


-- ============================================
-- RESUMO POR CURSO E STATUS
-- ============================================
SELECT
    C.NOME AS CURSO,
    QS.STATUS,
    COUNT(*) AS TOTAL
FROM QUESTAO_STAGING QS
JOIN PROVA P ON P.ID = QS.PROVA_ID
JOIN CURSO C ON C.ID = P.CURSO_ID
GROUP BY C.NOME, QS.STATUS
ORDER BY C.NOME, QS.STATUS;


-- ============================================
-- TOTAL DE QUESTÕES POR CURSO
-- ============================================
SELECT
    C.NOME AS CURSO,
    COUNT(*) AS TOTAL
FROM QUESTAO_STAGING QS
JOIN PROVA P ON P.ID = QS.PROVA_ID
JOIN CURSO C ON C.ID = P.CURSO_ID
GROUP BY C.NOME
ORDER BY C.NOME;

-- ============================================
-- O QUE NÃO ESTÁ COMO COMPLETA
-- ============================================
SELECT
    C.NOME AS CURSO,
    QS.NUMERO,
    QS.STATUS,
    QS.CONFIANCA,
    QS.PARSE_STRATEGY,
    QS.OBSERVACAO
FROM QUESTAO_STAGING QS
JOIN PROVA P ON P.ID = QS.PROVA_ID
JOIN CURSO C ON C.ID = P.CURSO_ID
WHERE QS.STATUS <> 'COMPLETA'
ORDER BY C.NOME, QS.NUMERO;



DROP TABLE GABARITO, ALTERNATIVA, QUESTAO, PROVA, CURSO, ANO CASCADE;